## Chapter#4 [NumPy Basics: Arrays and Vectorized Computation]

## package
package bohot saari files ko 1 sat jama kardenge to usko hum package kehte hain

## Class#2

In [4]:
import numpy as np

In [9]:
arr1 = np.array([1,23,34,34,4,5,5,6,3,7,34,2,1,1,5,4,2,6])
arr1

array([ 1, 23, 34, 34,  4,  5,  5,  6,  3,  7, 34,  2,  1,  1,  5,  4,  2,
        6])

In [13]:
# np.argsort()   >>> ye wo indices return karta hai jo is array ko sort kardega
# arr1.argsort()
np.argsort(arr1)

array([ 0, 13, 12, 11, 16,  8,  4, 15,  6, 14,  5,  7, 17,  9,  1, 10,  3,
        2], dtype=int32)

In [14]:
arr2 = np.array([1,23,34,34,4,5,5,6,3,7,34,2,1,1,5,4,2,6]).reshape(6,3)
arr2

array([[ 1, 23, 34],
       [34,  4,  5],
       [ 5,  6,  3],
       [ 7, 34,  2],
       [ 1,  1,  5],
       [ 4,  2,  6]])

In [21]:
# axis 1 pe sort karta hai means row wise dekh rha hai axis 0 col wise karega
# np.argsort(arr2,axis=1)
np.argsort(arr2)   # by default axis 1

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1],
       [2, 0, 1],
       [0, 1, 2],
       [1, 0, 2]], dtype=int32)

In [22]:
np.argsort(arr2,axis=0)

array([[0, 4, 3],
       [4, 5, 2],
       [5, 1, 1],
       [2, 2, 4],
       [3, 0, 5],
       [1, 3, 0]], dtype=int32)

In [23]:
arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
arr

array([[ 8,  2, -2],
       [-4,  1,  7],
       [ 6,  3,  9]])

In [42]:
arr[:1].argsort()

array([[2, 1, 0]], dtype=int32)

In [44]:
arr[arr[:, 1].argsort()]

array([[-4,  1,  7],
       [ 8,  2, -2],
       [ 6,  3,  9]])

In [47]:
arr[arr[1:2,].argsort()]

array([[[ 8,  2, -2],
        [-4,  1,  7],
        [ 6,  3,  9]]])