In [2]:
import numpy as np

# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
arr1d = np.arange(10)
print(arr1d)

arr2d = arr1d.reshape(2,5)
print(arr2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [10]:
arr1 = np.arange(10).reshape(2,5)
print(arr1)

arr2 = np.ones((2,5), dtype="int32")
print(arr2)

print("========================================")

stackedArr = np.vstack((arr1,arr2))

print(stackedArr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [11]:
arr1 = np.arange(10).reshape(2,5)
print(arr1)

arr2 = np.ones((2,5), dtype="int32")
print(arr2)

print("========================================")

stackedArr = np.hstack((arr1,arr2))

print(stackedArr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [18]:
arr = np.arange(10).reshape(2,5)

print(arr)

arr = np.ravel(arr)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [19]:
arr = np.arange(15).reshape(3,5)
print(arr)

arr = arr.ravel()
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [21]:
arr1d = np.arange(15)
print(arr1d)

arr2d = arr1d.reshape(5,3)
print(arr2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [27]:
arr = np.arange(25).reshape(5,5)
print(arr)
print("=====================")
arr = np.square(arr)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [29]:
arr = np.arange(30).reshape(5,6)
print(arr)
print("=====================")
arrMean = np.mean(arr)
print(arrMean)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [30]:
arrSD = np.std(arr)

print(arrSD)

8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [31]:
arrMed = np.median(arr)
print(arrMed)

14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [32]:
arrT = np.transpose(arr)
print(arrT)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [37]:
# .trace will sum all diagonal elements and diag() or diagonal() functions returns all diagonal elements

arr = np.arange(16).reshape(4,4)
print(arr)

print("=====================")

diagonalArr = np.diag(arr)
print(diagonalArr)
print("==========================")

diagonalSum = arr.trace()
print(diagonalSum)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  5 10 15]
30


## Question:13

### Find the determinant of the previous array in Q12?

In [43]:
from numpy.linalg import det

arrDet = det(arr)

print(arrDet)

0.0


## Question:14

### Find the 5th and 95th percentile of an array?

###### `n = (P/100) x N`
###### ` `
* n = ordinal rank of a given value
* P = percentile
* N = number of values in a data set (sorted from smallest to largest)

In [46]:
print(arr)

np.percentile(arr, (5, 95))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0.75, 14.25])

## Question:15

### How to find if a given array has any null values?

In [62]:
# we can use isnan() function to find the value that is not a number e.g:

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

np.isnan(arr)

[[1 2 3]
 [4 5 6]]


array([[False, False, False],
       [False, False, False]])