# 50 methods or attributes in numpy

In [3]:
import numpy as np

### 1) `np.random.randn()`
Generate random data

In [4]:
data = np.random.randn(3,3)
data

array([[ 0.77915242, -0.59998399,  0.24579592],
       [ 0.11635178, -0.97826938, -0.9372829 ],
       [-1.16615231,  1.07065078,  0.82991075]])

### 2) `.size`
We can find size of any array using `.size` attribute

In [12]:
data.size

9

### 3) `.shape`
we can find shape of array using `.shape` attribute

In [13]:
data.shape

(3, 3)

### 4) `.dtype`
We can also find data type of array using `.dtype` attribute

In [15]:
data.dtype

dtype('float64')

### 5) `np.array()`
* We can create an array using `np.array()` method
* We can pass in any sequence and this method will convert our input sequence to numpy array

In [7]:
list1 = [1,2,3,4,5,6,7,8,9]
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 6) `np.arange()`
We can also create an array using `np.arange()` function, it works similar to python range function

In [23]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### 7) `.ndim`
We can find number of dimensions of any array using `.ndim` attribute

In [16]:
arr.ndim

1

### 8) `np.zeros()`
Create zeros array of desired shape

In [17]:
zerosArr = np.zeros((4,2))
zerosArr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### 9) `np.ones()`
We can create ones array

In [19]:
onesArr = np.ones((5,5))
onesArr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 10) `np.empty()`
We can create an empty array

In [21]:
emptyArr = np.empty((2,2,3))
emptyArr

array([[[1.50708341e-312, 0.00000000e+000, 8.76794447e+252],
        [2.15895723e+227, 6.48224638e+170, 3.67145870e+228]],

       [[1.13260488e-095, 9.03292329e+271, 9.08366793e+223],
        [1.41075687e+232, 1.16070543e-028, 7.56602524e-307]]])

### 11) `np.full()`
We can create an array and fill our desired value to all its elements using `np.full()`

In [27]:
fullArr = np.full((5,4),3)
fullArr

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

### 12) `identity`
We can create identity matrix using `np.eye()` or `np.identity()`

In [29]:
idenArr = np.identity(5)
idenArr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 13) `astype()`
We can convert dtype of an array to other dtype

In [30]:
idenArr1 = idenArr.astype(np.int32)
idenArr1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### 14) `np.copy()`
We can make copy of the array

In [32]:
copy1 = np.copy(idenArr1)
copy1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### 15) `.T`
We can transpose an array using `.T` attribute or `np.transpose()` method

In [42]:
arr = np.arange(32).reshape(2,16)
print(arr)
arr.transpose()

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]]


array([[ 0, 16],
       [ 1, 17],
       [ 2, 18],
       [ 3, 19],
       [ 4, 20],
       [ 5, 21],
       [ 6, 22],
       [ 7, 23],
       [ 8, 24],
       [ 9, 25],
       [10, 26],
       [11, 27],
       [12, 28],
       [13, 29],
       [14, 30],
       [15, 31]])

### 16) `np.reshape()`
We can reshape our array

In [37]:
newArr = np.arange(32).reshape(4,4,2)
newArr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

### 17) `np.sqrt()`
We can find square root of an array

In [43]:
print(arr)
np.sqrt(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]]


array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
        3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
        4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436]])

### 18) `np.exp()`
We can find exponent of array

In [44]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
        1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
        4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
        1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13]])

### 19) `np.maximum()`
We can compute element wise maximum of array

In [46]:
arr1 = np.arange(11,21)
arr2 = np.arange(1,11)
print(arr1)
print(arr2)
np.maximum(arr1,arr2)

[11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10]


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### 20) `np.mpdf()`
We can separate fractional part and whole part of floating point array

In [57]:
emptyArr = np.empty((3,2))
print(emptyArr)
print("================")
remainder, whole = np.modf(emptyArr)
print(remainder)
print(whole)

[[0.00000000e+000 1.95451324e+184]
 [0.00000000e+000 1.51135519e+160]
 [0.00000000e+000 0.00000000e+000]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.00000000e+000 1.95451324e+184]
 [0.00000000e+000 1.51135519e+160]
 [0.00000000e+000 0.00000000e+000]]


### 21) `np.square()`
We can find sqaure of elments

In [60]:
print(arr)
np.square(arr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]]


array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
        169, 196, 225],
       [256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784,
        841, 900, 961]], dtype=int32)

### 22) `np.sign()`
We can calculate sign of each element in array

In [61]:
np.sign(arr)

array([[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 23) `np.abs()`
We can caluculate absolute value

In [62]:
np.abs(arr)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

### 24) `np.ceil()`
We can compute ceiling of each element

In [72]:
array = np.array([2.5666, 6.888,7.99999,4.888])
np.ceil(array)

array([3., 7., 8., 5.])

### 25) `np.floor()`
We can also compute floor of each element

In [73]:
np.floor(array)

array([2., 6., 7., 4.])

### 25) `np.rint()`
We can round the elements with dtype preserving

In [74]:
np.rint(array)

array([3., 7., 8., 5.])

### 26) `np.isnan()`
We can check if any elment is not a number

In [75]:
np.isnan(array)

array([False, False, False, False])

### 27) `np.add()`
We can add corresponding members of two arrays

In [76]:
arr1 = np.arange(11,21)
arr2 = np.arange(1,11)
print(arr1)
print(arr2)
np.add(arr1,arr2)

[11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10]


array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

### 28) `np.subtract()`
We can subtract elements from 1st array

In [77]:
np.subtract(arr1,arr2)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

### 29) `np.multiply()`
We can multiply two arrays

In [78]:
np.multiply(arr1,arr2)

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

### 30) `np.divide()`
We can divide arrays

In [79]:
np.divide(arr1,arr2)

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ,
        2.66666667,  2.42857143,  2.25      ,  2.11111111,  2.        ])

### 31) np.power()
We can raise power by using 2nd array

In [80]:
np.power(arr1,arr2)

array([         11,         144,        2197,       38416,      759375,
          16777216,   410338673, -1864941312,   565150579,   797966336],
      dtype=int32)

### 32) `np.minimum()`
We can find minum between two arrays

In [81]:
np.minimum(arr1,arr2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 33) `np.max()`
we can find largest value in array

In [82]:
np.max(arr1)

20

### 34) `np.min()`
We can find smallest number in array

In [83]:
np.min(arr1)

11

### 35) `np.argmax()`
We can find position of largest value

In [85]:
np.argmax(arr1)

9

### 36) `np.argmin()`
We can find position of min value

In [86]:
np.argmin(arr1)

0

### 37) `np.where()`
short form of ternary expression

In [90]:
#Suppose we want all values that are less than 5 should be equal to 100
print(arr2)
np.where(arr2 < 5, 100, arr2)

[ 1  2  3  4  5  6  7  8  9 10]


array([100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### 38) `np.mean()`
We can find mean of array

In [91]:
print(arr1)
np.mean(arr1)

[11 12 13 14 15 16 17 18 19 20]


15.5

### 39) `np.sum()`
We can find sum

In [93]:
np.sum(arr1)

155

### 40) `np.cumsum()`
We can find cumulative sum

In [94]:
np.cumsum(arr1)

array([ 11,  23,  36,  50,  65,  81,  98, 116, 135, 155], dtype=int32)

### 41) `np.std()`
We can find standard deviation

In [95]:
np.std(arr1)

2.8722813232690143

### 42) `np.var()`
We can find variance

In [97]:
np.var(arr1)

8.25

### 43) `cumprod()`
We can find cumulative product

In [98]:
np.cumprod(arr1)

array([        11,        132,       1716,      24024,     360360,
          5765760,   98017920, 1764322560, -837609728,  427674624],
      dtype=int32)

### 44) `np.any()`
We can check whether one or more value is True in array

In [100]:
array1 = np.array([True,False,True,True])
np.any(array1)

True

### 45)`np.all()`
We can check whether all values are True

In [101]:
np.all(array1)

False

### 46) `np.sort()`
We can sort the array

In [104]:
array1 = np.array([23,21,1,2,3,4])
print(array1)
np.sort(array1)

[23 21  1  2  3  4]


array([ 1,  2,  3,  4, 21, 23])

### 47) `np.unique()`
We can find unique values in array

In [107]:
array1 = np.array([23,21,21,21,1,2,3,4])
print(array1)
np.unique(array1)

[23 21 21 21  1  2  3  4]


array([ 1,  2,  3,  4, 21, 23])

### 48) `np.intersect1d()`
We can find common items between two arrays

In [110]:
print(arr1)
arr3 = np.array([12,22,1,12,17,20])
print(arr3)
print("==================")
np.intersect1d(arr1,arr3)

[11 12 13 14 15 16 17 18 19 20]
[12 22  1 12 17 20]


array([12, 17, 20])

### 49) `np.union1d()`
We can find union

In [111]:
np.union1d(arr1,arr2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### 50) `setxor1d()`
We can find symmetric difference

In [113]:
print(arr1)
print(arr3)
np.setxor1d(arr1,arr3)

[11 12 13 14 15 16 17 18 19 20]
[12 22  1 12 17 20]


array([ 1, 11, 13, 14, 15, 16, 18, 19, 22])