# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [5]:
vector1 = np.arange(10, 50)
vector1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [6]:
np.shape(vector1)

(40,)

5. Print the type of the previous array in question 3

In [7]:
print(type(vector1))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [9]:
print(np.__version__)

1.18.5


7. Print the dimension of the array in question 3


In [11]:
print(np.shape(vector1))

(40,)


8. Create a boolean array with all the True values

In [12]:
bool_arr = np.array([True, True, True])
bool_arr

array([ True,  True,  True])

9. Create a two dimensional array




In [13]:
arr2d = np.array([[1,2,3], [4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [14]:
arr3d = np.array([[[1,2,3], [4,5,6]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [16]:
vectorArr = np.arange(10)
print(vectorArr)
vectorArr = np.flip(vectorArr)
print(vectorArr)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [21]:
null_vector1 = np.zeros(10)
null_vector1[4] = 1
null_vector1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [22]:
arr = np.array([1, 2, 3, 4, 5], dtype="float64")
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [23]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

# multiplying

mult_arr = arr1 * arr2
mult_arr

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]]) 
                    
arr2 = np.array([[0., 4., 1.], 
                 [7., 2., 12.]])

#######How to COMPARE ???????????????????????????????????

17. Extract all odd numbers from arr with values(0-9)

In [34]:
arr = np.arange(0, 10)
odd_arr = arr[arr % 2 == 1]
odd_arr

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [37]:
# odd_arr = np.where(odd_arr % 2 == 1, -1, odd_arr)     #######same#########

odd_arr = np.where(odd_arr, -1, odd_arr)
odd_arr

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [75]:
# it is unclear what to do ?
# according to me it says that we have to replace the indexes of 5,6,7,8 to 12
# so I change the given indices to number 12

arr = np.arange(10)

arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [66]:
arr2d = np.ones(9, dtype="int32").reshape(3,3)
arr2d[1:2, 1:2] = 0
arr2d

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [68]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d = np.where(arr2d == 5, 12, arr2d)
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [16]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype="float64")

print(arr3d.dtype)


float64


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [3]:
arr2d = np.arange(0,10).reshape(2,5)
print(arr2d)
print("========")
slicedArr = arr2d[0,0:]
print(slicedArr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [5]:
arr2d = np.arange(0,10).reshape(2,5)
print(arr2d)
print("========")
slicedArr = arr2d[1:2,1]
print(slicedArr)    

[[0 1 2 3 4]
 [5 6 7 8 9]]
[6]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [8]:
arr2d = np.arange(0,10).reshape(2,5)
print(arr2d)
print("========")
slicedArr = arr2d[:,2:3]
print(slicedArr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [32]:
randArr = np.fabs(np.random.randn(10,10) * 10).astype(np.int32)
print(randArr)
print("=============================================")
print(f"min value of array is { randArr.min() }")
print(f"max value of array is { randArr.max() }")

[[25  7 17  4  8  0 23  0 13  1]
 [ 9  2  9  7 17 13 10  4  3  6]
 [ 4  0  2  2  4  4  8  5  1  6]
 [ 4  9 10  4  4  2  4 29 11  7]
 [30  7 13  1  8 10  6 26  0  3]
 [ 2 14  3  5 11 10  2  3 12  5]
 [ 0 13  4  1  8  3 24  1  0 16]
 [12  9  7  4  0  3  2  8 10  3]
 [ 9 18  3  7  4  5 14  4  1 15]
 [ 0 11  5 18  1  2  7  7  4  8]]
min value of array is 0
max value of array is 30


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b
#### `Important`

In [33]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
commonItems = np.intersect1d(a,b)
print(commonItems)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match

##### `Important`

In [37]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int32),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [39]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print("=================================================================")
print(data)
print("==================================================================")
data[names != "Will"]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.79393329 -0.24655811  0.25146772  0.79094022]
 [-0.74122081  0.3128366   1.09889867  0.06778412]
 [ 1.59392552 -1.78721859  1.36199997 -0.70207021]
 [ 0.00385504 -1.77486425  0.28350262 -0.68331656]
 [ 0.56781202  0.44551843  0.20804412 -0.43192636]
 [-0.39929525 -0.50807885  1.22369484 -0.46889761]
 [ 0.91936049 -1.45236754  0.44942658  0.87551987]]


array([[-0.79393329, -0.24655811,  0.25146772,  0.79094022],
       [-0.74122081,  0.3128366 ,  1.09889867,  0.06778412],
       [ 0.00385504, -1.77486425,  0.28350262, -0.68331656],
       [-0.39929525, -0.50807885,  1.22369484, -0.46889761],
       [ 0.91936049, -1.45236754,  0.44942658,  0.87551987]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [40]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print("=================================================================")
print(data)
print("==================================================================")
data[(names != "Will") & (names != "Joe")]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.2054284  -0.23492557 -1.88894665  0.6798853 ]
 [-0.56147708 -0.93584448  0.47066819  1.59661609]
 [ 1.56863924 -0.13476495 -0.97011241 -0.23259412]
 [ 1.55182777 -0.63334647 -0.08475968 -0.36532178]
 [ 0.18813797 -0.8723048  -0.19177223 -0.83987391]
 [ 0.74001615  0.08093223 -0.42358816 -0.15924867]
 [ 0.58832996 -1.42472551 -0.66089854  1.119267  ]]


array([[-1.2054284 , -0.23492557, -1.88894665,  0.6798853 ],
       [ 1.55182777, -0.63334647, -0.08475968, -0.36532178]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [50]:
arr2d = np.arange(1,16).reshape(5,3)
print(arr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [2]:
arr = np.arange(1,17,dtype="float64").reshape(2,2,4)
print(arr)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [53]:
np.transpose(arr)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [57]:
arr = np.arange(10)
sqrtArr = np.sqrt(arr)
print(sqrtArr)
np.where(sqrtArr < 0.5, 0, sqrtArr)
print("=======================")
print(sqrtArr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [63]:
randArr1 = np.random.randn(12)
randArr2 = np.random.randn(12)

print(randArr1)
print("========================================")
print(randArr2)

maxedArr = np.maximum(randArr1,randArr2)
print("=========================================")
print(maxedArr)

[ 1.62443203 -1.40926474 -1.05645206  0.11376982  1.73433132 -0.11038637
  0.57450415 -0.36751264  0.8188288   0.66586083  0.12317565  1.4998674 ]
[ 0.50921273  0.35832863 -1.46525208  1.18001725  0.37401588  1.04356936
  0.83457493 -0.04411408  0.65177594  0.77496305  0.6816725   1.05197444]
[ 1.62443203  0.35832863 -1.05645206  1.18001725  1.73433132  1.04356936
  0.83457493 -0.04411408  0.8188288   0.77496305  0.6816725   1.4998674 ]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniqueArr = np.unique(names)
print(uniqueArr)
uniqueArr.sort()
print(uniqueArr)

['Bob' 'Joe' 'Will']
['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b

#### `Important`

In [9]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

a = np.delete(a, np.where(a == np.intersect1d(a,b)))
print(a)
print(b)

[1 2 3 4]
[5 6 7 8 9]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [11]:
sampleArray = np.array([[34,43,73],
                        [82,22,12],
                        [53,94,66]])

newColumn = np.array([[10,10,10]])

np.delete(sampleArray, sampleArray[:,1])
sampleArray[:,1] = newColumn

print(sampleArray)


[[34 10 73]
 [82 10 12]
 [53 10 66]]


<ipython-input-11-5077ef9b03bd>:7: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  np.delete(sampleArray, sampleArray[:,1])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [32]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [31]:
randArr = np.abs(np.random.randn(20) * 10)
cumSum = randArr.cumsum()
cumSum

array([ 18.98218852,  31.0212585 ,  35.44932941,  38.39677111,
        39.75084232,  42.45801391,  44.29112041,  47.507897  ,
        50.80131013,  55.46342595,  66.78502155,  75.37839693,
        85.55048903, 106.79203806, 107.87435641, 122.53512593,
       129.38431575, 139.86633041, 153.19283794, 155.78103835])